sudo: required
services:
- docker
language:  bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t beckonconn/arm-bind .
- docker run beckonconn/arm-bind named --version
