sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
services:
- docker
language:  bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t beckonconn/rpi-bind .
- docker run beckonconn/rpi-bind "-v"
after_success:
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u $dockerUser -p $dockerPass
    docker tag beckonconn/rpi-bind beckonconn/rpi-bind:$COMMIT
    docker push beckonconn/rpi-bind:$COMMIT
    docker push beckonconn/rpi-bind
  fi
